### ISSUE TITLE
raspberrypi-kernel sets INITRD=No

### ISSUE THREAD

**Issue by mutability** [RPi-Distro/firmware#1]
The raspberrypi-kernel package sets INITRD=No before running postinst kernel hooks.
This means that update-initramfs never gets run even when an initrd is in use.

Is there a good reason for disabling that functionality?
Can you remove the INITRD=No setting from the kernel packaging?

**Comment by XECDesign** [comment]
Since the raspberrypi.org image of raspbian does not need or use initramfs, it needs to be an opt-in rather than an opt-out feature. For now, you can change the value of `INITRD` in `/etc/kernel/*/initramfs-tools`. What would be your preferred way to opt in?
Another problem is that it will create files which need to be referenced from `config.txt` and their names will change. That will make some systems fail to boot properly. There would need to be another hook to update `config.txt`.

**Comment by mutability** [comment]
A simple config file in `/etc` that let you set this without having to mangle the package-provided initramfs-tools hooks would be good. I need to set this in an automated way and messing with shellscript post-package-install is not fun.

The hook points that you can use to update `config.txt` already exist (`/etc/initramfs/post-update.d`, plus the kernel hooks). The problem is just that `update-initramfs` never gets called. Current hookscript WIP is here: https://github.com/flightaware/piaware-support/blob/b24c9c0d5abe8f3fd6e550a16910c5b55f90ff8e/scripts/rpi-bootconfig

I work around the current packaging problem by bypassing the `INITRD` check entirely, which is NVG as a permanent solution: https://github.com/flightaware/piaware-support/blob/b24c9c0d5abe8f3fd6e550a16910c5b55f90ff8e/etc/kernel/postinst.d/rpi-bootconfig#L14

**Comment by XECDesign** [comment]
I have been leaning towards a /etc/default/raspberrypi-kernel.

One of the features of Raspbian is that you can take an up-to date card out and run it on any other pi. After talking to the firmware/kernel devs, the suggested solution was automatically loading initrd(7/8).img, if they are present. An alternative would be using conditional filters in config.txt, but that gets ugly fairly quickly since all automated updates to config.txt would then have to be aware of conditional filters.

The remaining problem is that a set of initrd(7/8).img files does not fit nicely with the way initramfs-tools works. Then perhaps the additional hook would need to rename the generated files. Would you happen to know if that is likely to cause problems? I can imagine a case where initramfs tries to update initramfs, but runs into trouble because the previous file has been moved. I'd need to set aside some testing time for such issues.

**Comment by mutability** [comment]
`/etc/default/raspberrypi-kernel` would be perfect.

I don't mind handling `config.txt` myself, but if you wanted to use the rpi-bootconfig script linked above as a starting point for building something into the Raspbian images that would be fine. It does handle different hardware via a selfcontained set of filter sections and will deal with the initramfs images being named differently for different kernel versions etc.

Anything touching `config.txt` has to be willing to deal with filters or it's broken anyway (`raspberrypi-sys-mods`, I'm looking at you..)

Renaming the initramfs images is not going to play well with initramfs-tools. update-initramfs maintains a sha1 of the images it generates and will refuse to update them automatically if they're changed or missing.

**Comment by XECDesign** [comment]
Just pushed firmware with the appropriate change.

I don't want to change the default behaviour of initramfs-tools and annoy all the people who rely on it. So I've settled on making sure that works as intended upstream and adding a forked version at some later date that will  create appropriately named files in /boot.

/etc/default/raspberrypi-kernel:
```
# Defaults for raspberrypi-kernel

# Uncomment the following line to enable generation of
# /boot/initrd.img-KVER files (requires initramfs-tools)

#INITRD=Yes

# Uncomment the following line to enable generation of
# /boot/initrd(7).img files (requires rpi-initramfs-tools)

#RPI_INITRD=Yes
```

Hopefully that's fairly self-explanatory.

**Comment by glubsy** [comment]
I gather this is not yet functional? Couldn't find rpi-initramfs-tools in the repos. 

I assume `INITRD=Yes` works at least. For now I've been doing manual update of my initramfs. So updating cmdline.txt accordingly manually too. :)

**Comment by XECDesign** [comment]
`INITRD=Yes` is untested and unsupported and `RPI_INITRD` is shelved for now.

**Comment by glubsy** [comment]
I understand. Thanks!
